# Generated by Django 5.2.7 on 2025-10-15 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Busqueda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termino_buscado', models.CharField(max_length=100)),
                ('fecha_busqueda', models.DateTimeField(auto_now_add=True)),
                ('encontro_resultados', models.BooleanField(default=False)),
                ('genero_alerta', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='busquedas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(blank=True, max_length=255, null=True)),
                ('identificacion', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_lista', models.CharField(blank=True, max_length=100, null=True)),
                ('origen_lista', models.CharField(blank=True, max_length=100, null=True)),
                ('relacionado_con', models.TextField(blank=True, null=True)),
                ('fuente', models.CharField(blank=True, max_length=255, null=True)),
                ('es_restrictiva', models.BooleanField(default=False)),
                ('busqueda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='consultas.busqueda')),
            ],
        ),
    ]
